### ISSUE TITLE
Add support for slang

### ISSUE THREAD

**Issue by mithro** [a2k-hanlon/linter-veriloghdl#2]
You might also want to checkout [slang](https://github.com/MikePopoloski/slang)

> slang is a software library that provides various components for lexing, parsing, type checking, and elaborating SystemVerilog code. It comes with an executable tool that can compile and lint any SystemVerilog project, but it is also intended to be usable as a front end for synthesis tools, simulators, linters, code editors, and refactoring tools.
> 
> Full documentation is available on the website: https://sv-lang.com

**Comment by a2k-hanlon** [comment]
I have started working on support for slang, thanks for the suggestion! Development is happening in the slang branch. As of now I think I have slang talking with the linter properly, but I still have to iron out some details.

**Comment by a2k-hanlon** [comment]
I've now ironed out the issues I found, and published a new minor release with support for slang (952b73f).
